version: "3.8"

volumes:
  database:

networks:
  public:
  private:
    internal: true

services:
  cdn:
    restart: always
    container_name: cdn.localhost
    image: architecture:cdn
    ports:
      - 3000:3000
    networks:
      - public
    build:
      dockerfile: deploy/services/Dockerfile.cdn
      context: ../../

  task:
    restart: always
    container_name: task.localhost
    image: architecture:task
    ports:
      - 3001:3000
    networks:
      - public
      - private
    build:
      dockerfile: deploy/services/Dockerfile.task
      context: ../../
    volumes:
      - database:/var/run/app/.db
      
  user:
    restart: always
    container_name: user.localhost
    image: architecture:user
    ports:
      - 3002:3000
    networks:
      - public
      - private
    build:
      dockerfile: deploy/services/Dockerfile.user
      context: ../../
    volumes:
      - database:/var/run/app/.db

  # sql
  #    networks:
  #    - private
  #